import Link from "next/link";
import { MarketingPage } from "@/components/marketing/marketing-page";
import { brand } from "@/config/brand";

export const metadata = { title: "Privacy Policy", description: `How ${brand.APP_NAME} handles personal data.` };
const C = brand.COMPANY_NAME, P = brand.APP_NAME;

export default function PrivacyPage() {
  return (
    <MarketingPage title="Privacy Policy" updated="10 October 2026" intro={`How ${C} handles personal data in ${P}.`}>
      <p>{P} is a product of {C}. This policy explains what we collect, why, and the choices you have, in line with the Nigeria Data Protection Act 2023 and similar laws that apply to you.</p>
      <h2>Our two roles</h2>
      <ul>
        <li><strong>As a service provider (processor)</strong> for the logistics companies that use {P}: we process shipment, customer, recipient, driver, location and financial data only on their instructions. The company that runs your delivery is responsible for that data and for answering your requests about it; if you contact us about it we will pass your request to them.</li>
        <li><strong>As a controller</strong> for account holders&apos; sign-up, security, billing and website usage data, which we use to run and protect the service.</li>
      </ul>
      <h2>What we collect</h2>
      <ul>
        <li>Account data: name, work email, phone, company name, role, password (stored only as a salted hash) and two-factor settings.</li>
        <li>Operational data entered or generated by your company: shipments, sender and recipient names, phones, addresses, delivery proof (signatures, photos, one-time codes), driver GPS positions during active shifts, cash-on-delivery and invoice records, documents and audit logs.</li>
        <li>Billing data: plan, payment references and the last four digits and brand of a saved card. Card details themselves are handled by our payment provider.</li>
        <li>Technical data: IP address, device and browser details, and security events such as failed sign-ins.</li>
      </ul>
      <h2>How we use it</h2>
      <p>To provide and secure the service; to authenticate users and prevent abuse; to send service messages (such as password resets, delivery notifications your company enables, and billing notices); to process payments; to provide support; and to meet legal obligations. We do not sell personal data and do not use Customer Data for advertising.</p>
      <h2>Who we share it with</h2>
      <p>Only service providers needed to run {P}, under confidentiality and data-protection terms: cloud hosting and database providers, our payment processor, and email, SMS, WhatsApp, push-notification and mapping providers that you or we enable. We may also disclose data where the law requires it.</p>
      <h2>Location data</h2>
      <p>Driver apps share a driver&apos;s GPS position with their company while they are on shift. Drivers can go offline to stop sharing. Companies must tell their drivers about this.</p>
      <h2>International transfers</h2>
      <p>Our providers may process data outside Nigeria. Where they do, we rely on contractual and technical safeguards appropriate to the Nigeria Data Protection Act.</p>
      <h2>Retention</h2>
      <p>Customer Data is kept while the workspace is active and for up to 30 days after termination for export, then deleted or anonymised unless we must keep it by law. Audit logs and billing records may be kept longer where the law requires.</p>
      <h2>Security</h2>
      <p>Each company&apos;s data is logically separated and access-controlled by role. Passwords are hashed, sessions can be revoked, optional two-factor authentication is available, connections use TLS, and sensitive actions are recorded in an append-only audit log. No system is perfectly secure; we will notify affected customers of a breach as the law requires.</p>
      <h2>Your rights</h2>
      <p>You may ask to access, correct, delete, restrict or port your personal data, object to certain processing, or withdraw consent, and you may complain to the Nigeria Data Protection Commission. For data held by a logistics company, contact that company first. For data we control, write to <a href={`mailto:${brand.PRIVACY_EMAIL}`}>{brand.PRIVACY_EMAIL}</a>.</p>
      <h2>Cookies</h2>
      <p>We use a small number of essential cookies to keep you signed in and secure the service. We do not use advertising cookies.</p>
      <h2>Children</h2>
      <p>{P} is for business use and is not directed at children.</p>
      <h2>Changes and contact</h2>
      <p>We will post changes to this policy here and notify account owners of material changes. See also our <Link href="/terms">Terms of Service</Link>. Contact: {C}{brand.COMPANY_ADDRESS ? `, ${brand.COMPANY_ADDRESS}` : ""}, <a href={`mailto:${brand.PRIVACY_EMAIL}`}>{brand.PRIVACY_EMAIL}</a>.</p>
    </MarketingPage>
  );
}
